### ISSUE TITLE
Asset named "' + name + '" was overwritten because of naming collision

### ISSUE THREAD

**Issue by kikoanis** [halt-hammerzeit/webpack-isomorphic-tools#11]
I see you are checking @ this line 
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/48533b5db3d6864dc1f26d4d9fce67e9bd28aa07/source/helpers.js#L2

for the existence of a parsed asset and you print out an error message if it is already exists. Now if the parsed asset was an empty object (i.e {}) this would be a problem and the message would be misleading.

Not sure if it should check for the emptiness of the object before displaying the message or even before assigning the parsed asset to set[name] @
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/c20c11456be2dcc3d80a2ce88796de406d6f879d/source/plugin/write%20assets.js#L199

**Comment by halt-hammerzeit** [comment]
@kikoanis That error message basically means that either the `naming` function or the `filter` function are not specific enough. Technically an empty object doesn't have any meaning and rewriting it could be ok but I think it would be better to let a developer know that his functions aren't specific enough.

**Comment by halt-hammerzeit** [comment]
Also see this discussion
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/10

**Comment by kikoanis** [comment]
Totally makes sense Actually I was getting this when trying to build react-redux-universal-hot-example and I only get the error messages on parsing "less" files (font-awsome files) so it might be an issue with webpack-isomorphic-tools.js config file. Will look more and see how it goes. Also, you might consider adding the file name (m.name) to the error message if the parsed file was empty for the message to be more informative.

**Comment by halt-hammerzeit** [comment]
@kikoanis that's a good idea and actually i've included some info already: you might try the `debug: true` flag

**Comment by kikoanis** [comment]
I see you figured out the real issue in this https://github.com/erikras/react-redux-universal-hot-example/pull/423

Thanks. closing...

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
