### ISSUE TITLE
Babel Runtime.

### ISSUE THREAD

**Issue by tom-drake** [halt-hammerzeit/webpack-isomorphic-tools#120]
Hi,

The babel runtime was removed a while ago, but it was added back in at: d64cc7c34131a6c72aed6282bd274cf2f4d9dad2

Was this intended?
Thanks

**Comment by halt-hammerzeit** [comment]
Hello.
I'm not sure why did I add it.
Does it work without it?
I didn't check.

**Comment by tom-drake** [comment]
Ill open a pull request :)

**Comment by tom-drake** [comment]
From what I can tell the babel runtime is required now. I tried without it in my project and it seems to just throw errors now.

**Comment by halt-hammerzeit** [comment]
Ok then, since it's server side, the only concern is the version of `babel-runtime`, so the possible issues can arise when Babel 7 is out and some people migrate to it while others preferring a more stable older version.
I'm not sure with all that NPM 3 stuff is it still installing different major versions of packages or is it now all flattened and global single version (I guess it's not).

**Comment by halt-hammerzeit** [comment]
Still it could conflict, say, when a person uses Babel 7 runtime in their app and then also `require()`s the tools which are using Babel 6, so apparently it's better not to use the runtime.
Maybe by the time Babel 7 is out Node.js matures enough to be able to handle the new ES6 syntax.
