### ISSUE TITLE
Issue loading multiple css files

### ISSUE THREAD

**Issue by reidblomquist** [halt-hammerzeit/webpack-isomorphic-tools#138]
Hello! First off - let me say thank you for your hard work on this awesome FOSS.

Hoping you can help me with this issue.

When following the style-loader docs to extract text two separate css files (very specific load order needed) - found here https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/webpack-1/README.md the static files are built properly into my dist, and my dev environment works as expected. However, when running in prod and using webpack-isomorphic-tools - we're only seeing a single css file load or be written to our webpack-assets.json and/or in our assets/style array.

Is there anything special we need to address this? We're following the proffered style-loader example. Any help is much appreciated!

Cheers

**Comment by halt-hammerzeit** [comment]
I haven't ever extracted two distinct CSS files using `extract-text-plugin` so it is possible that it only puts a single one into `webpack-assets.json`.
So I haven't checked such a use case.
You may try to debug it using `console.log` inside `path` and `filter` options to see if the second CSS file even gets there.
If it gets through `filter` and is correctly modified by `path` then you can debug the `parse` function to see if it correctly extracts the contents from `webpack-stats.json`.
Alternatively you can run in `debug: true` mode and see the console output and also search for the second file contents inside `webpack-stats.json` because this Webpack file is the source for `webpack-assets.json`

**Comment by sunsheeppoplar** [comment]
Did you ever make any headway with this @reidblomquist ?
