### ISSUE TITLE
Overriding require() hook for file extension .js

### ISSUE THREAD

**Issue by CalebEverett** [halt-hammerzeit/webpack-isomorphic-tools#18]
Hi, I am getting the following error on build:

````
[require-hook] [warning] -------------------------------------------------------------
[1] [require-hook] [warning] Overriding require() hook for file extension .js
[1] [require-hook] [warning] -------------------------------------------------------------
```

**Comment by halt-hammerzeit** [comment]
Hello.
It's not an error, it's a warning.
It means that you are overriding '.js' files loading logic.

**Comment by CalebEverett** [comment]
Hi, thank you,
What might be causing that?

On Wed, Nov 4, 2015 at 12:57 AM, Nikolay <notifications@github.com> wrote:

> Hello.
> It's not an error, it's a warning.
> It means that you are overriding '.js' files loading logic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/18#issuecomment-153644758>
> .
>



-- 
Caleb Everett
Career College of California
201 E. 4th Street, Suite 200
Santa Ana, CA 92701
(714) 243-8614 phone and fax
www.careercalifornia.edu

Facebook <http://www.facebook.com/CareerCalifornia> | Twitter
<http://twitter.com/careercalif> |  LinkedIn
<http://www.linkedin.com/company/941062> | G+
<https://plus.google.com/b/104968762557101611990/104968762557101611990/posts>

**Comment by halt-hammerzeit** [comment]
Well, you're most likely using an extension `.js` in your `assets`.
What is it for?

**Comment by CalebEverett** [comment]
I don't know what that would be. How can I identify the offending file?

**Comment by halt-hammerzeit** [comment]
You can start by posting your `webpack-isomorphic-tools` config

**Comment by CalebEverett** [comment]
[Here](https://github.com/CalebEverett/react-redux-universal-material/blob/22d707b9cee20fab294db7db86f0a8c180f6e4e8/webpack/webpack-isomorphic-tools.js) it is.

**Comment by halt-hammerzeit** [comment]
Well, yes, you are hooking into `.js` file require()ing
https://github.com/CalebEverett/react-redux-universal-material/blob/22d707b9cee20fab294db7db86f0a8c180f6e4e8/webpack/webpack-isomorphic-tools.js#L48
That's not a disaster, it's just a reminder.
Maybe I should make the warning less exclamative.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
