### ISSUE TITLE
SVGs are displayed as base64 strings

### ISSUE THREAD

**Issue by passionkind** [halt-hammerzeit/webpack-isomorphic-tools#2]
I'm using svg-inline loader for some svg icons. The component requires them inlined (as suggested by svg-inline loader). Using webpack-isomorphic-tools displays base64 strings inside those components.

Is there any way to fix / enhance this ?

Thank you so much !!!

**Comment by halt-hammerzeit** [comment]
Hello.
Can you give me some code samples?
I don't actually understand what you mean here.

`webpack-isomorphic-tools` by default will return the same thing as your webpack loader.
If your loader inlines svgs as base64 so will `require()` calls do.
Do you want some kind of custom server side behaviour?

**Comment by passionkind** [comment]
I fiddled around with it and finally got it working.

My issue is / was that I needed the *plain svg xml* code injected instead of a base 64 encoded string.
I'm using the (react-redux-universal-hot-example)[https://github.com/erikras/react-redux-universal-hot-example] project.

In this project, svg is being parsed via the url_loader_parser and encoded as base64 string.

I have added another `asset_type` and am using the same parser as you have set for scss files :

```js
svgs: {
      extension: "svg",
      parser: function(m, options) {
        if (m.source) {
          var regex = options.environment === 'production' ? /module\.exports = ((.|\n)+);/ : /exports\.locals = ((.|\n)+);/;
          var match = m.source.match(regex);
          return match ? JSON.parse(match[1]) : {};
        }
      }
    }
```

In combination with the svg-inline-loader in my webpack config, this seems to finally work as expected and I'll go with that solution.

Does that make sense from your understanding?

`webpack-isomorphic-tools` seems to be a really powerful thing ! I sadly don't have the time at the moment to have a deeper look at it. But thank you so much for putting your time and thoughts into it !

**Comment by halt-hammerzeit** [comment]
Oh, so you got it.
Yeah, I guess that will do.
The thing is, webpack-isomorphic-tools can get anything the specified webpack loader allows it to.
If a loader exposes file contents in it's `module` description (`.source` in this case) then you can use it as well.
If a loader didn't expose file contents in it's `module` variable then there would be no way for this particular loader to get file contents.
Another solution would be using `url-loader` with a very high `limit` parameter so that it wouldn't substitute files with base64.
As far as I can tell from `url-loader` source it's the only way to tell it not to extract base64 data:
https://github.com/webpack/url-loader/blob/master/index.js#L15

**Comment by halt-hammerzeit** [comment]
Or just use `file-loader` instead of `url-loader` because `url-loader`'s sole purpose is to return base64 for smaller files and resort to `file-loader` on the rest of the files

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
