### ISSUE TITLE
Writing debug stats despite the debug flag set to false

### ISSUE THREAD

**Issue by timdorr** [halt-hammerzeit/webpack-isomorphic-tools#21]
[Looks like this is the offending line](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/cdfa565b1be790ce51ebda10d5666afb8357a62f/source/plugin/write%20assets.js#L29). Shouldn't that be `if (debug) {`?

**Comment by halt-hammerzeit** [comment]
Yeah, it's always written in dev mode.
Maybe it should only be written in debug mode instead.
I think it should.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/write%20assets.js#L29

**Comment by timdorr** [comment]
[It was in the past](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/commit/dd871f3c91b7dd81f82edba5b201f71e7aa4c06d#diff-2a0e3920444cc02bd6467fe1dec4e22fL28). Thanks for the fix!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
