### ISSUE TITLE
Use with webpack-dev-middleware?

### ISSUE THREAD

**Issue by mattkrick** [halt-hammerzeit/webpack-isomorphic-tools#23]
I can't use webpack's dev server as is so I just include the webpack-dev-middleware in my server file, it looks something like this:
```
const compiler = webpack(config);
app.use(require('webpack-dev-middleware')(compiler, {
    noInfo: true,
    publicPath: config.output.publicPath
  }));
```
 The problem (I think) is that since I'm calling webpack-isomorphic-tools before the dev-server is set up, there's no stats file to be found & it just infinitely tries to find it (`[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)`). Is there a way to get the two to play nicely?

**Comment by halt-hammerzeit** [comment]
Well, you can try to start the dev-server first and see how it goes.

**Comment by mattkrick** [comment]
Yep, calling the server directly the first time around & then sending it through the `.server` callback works OK, just wasn't sure if there's a way to set this up as an express middleware or something similar.

**Comment by halt-hammerzeit** [comment]
to set up `webpack-isomorphic-tools` as a middleware?
that wouldn't be possible because it's not a middleware, it's a hacking device.

**Comment by mattkrick** [comment]
Yeah, you're right, I'm just thinking of some way to hook the reading/parsing/assets writing part to webpack right after it's built instead of just checking for it on an interval.

**Comment by halt-hammerzeit** [comment]
Well, if you find a way to know when its built - then I'll integrate your solution into the project

**Comment by bulby97** [comment]
Hey @mattkrick I have the same issue. Can you tell me exactly how did you do it ?

**Comment by mattkrick** [comment]
@bulby97 I explain it here: https://medium.com/@matt.krick/a-production-ready-realtime-saas-with-webpack-7b11ba2fa5b0#.rwva7ij4n

**Comment by bulby97** [comment]
@mattkrick Thank you !!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
