### ISSUE TITLE
webpack-assets.json

### ISSUE THREAD

**Issue by christiansakai** [halt-hammerzeit/webpack-isomorphic-tools#27]
Hello,

I am wondering why my css file is under assets property of the webpack-assets.json

```
/ isomorphic configuration

var path = require('path');
var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');

module.exports = {
  webpack_assets_file_path: '../build/webpack-assets.json',

  assets: {
    styles: {
      extension: 'css',
      filter: WebpackIsomorphicToolsPlugin.style_loader_filter,
      path: WebpackIsomorphicToolsPlugin.style_loader_path_extractor,
      parser: WebpackIsomorphicToolsPlugin.css_loader_parser
    }
  }
};
```

```
// result webpack-assets.json
{ javascript: { main: '/bundle.js' },
  styles: {},
  assets: { './common/components/index.css': 'body {\n  background: red;\n}\n\nh1 {\n  color: white;\n}' } }
```

shouldn't webpack-assets.json be this
```
// result webpack-assets.json
{ javascript: { main: '/bundle.js' },
  styles: { './common/components/index.css': 'body {\n  background: red;\n}\n\nh1 {\n  color: white;\n}' } }
```

**Comment by halt-hammerzeit** [comment]
It was in the past.
Now all assets are in the `assets` category.
`javascript` is for entry points, so is `styles`

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
