### ISSUE TITLE
Overloading issue on pre-transpiled code

### ISSUE THREAD

**Issue by Autarc** [halt-hammerzeit/webpack-isomorphic-tools#29]
Not sure if its directly related to this project or more [require-hacker](https://github.com/halt-hammerzeit/require-hacker), but there is an issue if the image/style tools are used with pre-babeled code. To reduce the memory overhead during runtime, gulp + Babel (5.X) is used. This causes following error on execution:
```js
Debug: internal, implementation, error 
    Error: Uncaught error: Cannot find module './App.styl'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function._module3.default._resolveFilename (.../node_modules/require-hacker/babel-transpiled-modules/require hacker.js:350:34)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```
If the original source code is used with runtime compilation via `require('babel-core/register')`
everything works fine.

**Comment by halt-hammerzeit** [comment]
Well, it clearly says `Cannot find module './App.styl'`
Is there a file `App.styl` in the same directory as the compiled file being run?

**Comment by Autarc** [comment]
Sorry - thought since the module syntax is used and the styles already included in the `webpack-assets.json`, that it doesn't require a real file. After adding it at the same directory it works.

**Comment by halt-hammerzeit** [comment]
I don't know, maybe we should rewrite this.

**Comment by halt-hammerzeit** [comment]
If you compile your files they are placed into some `build` folder.
All the relative `require()` paths are resolved there.
But you only copied `*.js` files there, omitting, for example, the `*.styl` files.

Technically there is a possibility to hack `require()` function in such a way that it won't look files up in the filesystem and will go straight to `webpack-assets.json`.
All the code is already written.
Maybe I'll make this change.
Some thinking is required.

**Comment by Autarc** [comment]
Sounds good, especially for assets which are already available as Strings (e.g. Base64 or Module-Objects) its more reasonable than referring to 'duplicates'.

**Comment by halt-hammerzeit** [comment]
Try it out and write here whether it works now

**Comment by halt-hammerzeit** [comment]
I changed my mind: I don't see a way for correctly resolving all the `require()`d paths from another folder: `require()` path resolution algorythm is based on current folder and when code is moved to another folder `require()` may yield a different result.

Until someone finds a way to perform an absolutely identical `require()` path resolution algorythm from another folder, this issue is considered unimplementable.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
