### ISSUE TITLE
Can't find the HTML file

### ISSUE THREAD

**Issue by yellowfish1220** [halt-hammerzeit/webpack-isomorphic-tools#34]
When I click the HTML file page to see the wroking example [webpack-isomorphic-tools](https://www.npmjs.com/package/webpack-isomorphic-tools#a-working-example) , 
I just get the 404 error: https://github.com/halt-hammerzeit/webapp/blob/master/code/client/html.js

**Comment by halt-hammerzeit** [comment]
Thanks, I updated the readme
https://github.com/halt-hammerzeit/webapp/blob/master/code/page-server/html.js

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
