### ISSUE TITLE
switching between development and production

### ISSUE THREAD

**Issue by ChiefORZ** [halt-hammerzeit/webpack-isomorphic-tools#43]
Hey,

thanks for the effort in this little plugin. this is definitely a part of webpack that is missing out-of-the-box.

anyways. i got an weird question... maybe i am using or understanding something not as intended.
you can take a look at my [repo](https://github.com/ChiefORZ/super-sexy-react). I've sucessfully implemented dynamically isomorphic chunks of js and css. I am doing my finishing touches to release a 'production-ready' version of it.

So, please try starting the server locally with `npm run dev`. It successfully bundles all dynamic chunks and offers it.
Next, stop the server and try to run the server in production with `npm start`. It bundles all chunks as well - with chunkhash names (for caching)... The server-side rendering is working too. But as soon as you open http://localhost:3000 - and open the console - you will see, that the server-side rendered `Html.jsx` is referencing to the chunk files previously build in development mode.

When you restart the production server, it will work fine.

It seems that `webpack-isomorphic-tools` is refferencing to the **`webpack-assets.json`** before the new files are even parsed by webpack and babel... (just an idea :D )

Just out of curiosity i cloned https://github.com/erikras/react-redux-universal-hot-example and tried the same thing - same behaviour.

Am I missing something? Thanks!

**Comment by halt-hammerzeit** [comment]
In your npm scripts there's no `webpack` command
https://github.com/ChiefORZ/super-sexy-react/blob/master/package.json#L17-L20
And because of that no webpack build is run.

**Comment by ChiefORZ** [comment]
easy as that.

thanks!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
