### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by Sridatta7** [halt-hammerzeit/webpack-isomorphic-tools#44]
I just upgraded my project to babel 6 and am receiving the following error.

*error given was: Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function._module3.default._resolveFilename (/Users/sridattap/Applications/frontend/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:403:34)*

Any plans to upgrade this project and require-hacker to babel 6??

**Comment by halt-hammerzeit** [comment]
You can make up a sample project illustrating the error and I can have a look at it.
I haven't even looked at Babel 6 yet.

**Comment by dtothefp** [comment]
@Sridatta7 I upgraded to Babel 6 and all works fine. One of the most major breaking changes was destructiring export default of an object in the import statement no longer works. That is most likely your problem but I can't know for sure

**Comment by dtothefp** [comment]
@Sridatta7 why do you care, isomorphic tools is precompiled (doesn't seem like this would be related to glob)? I just went through this at work and it was painful, would be happy to help out. I'm on Babel 6 and isomorphic tools works great, use https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
