### ISSUE TITLE
Using Handlebars templating over the server HTML component?

### ISSUE THREAD

**Issue by gerardmrk** [halt-hammerzeit/webpack-isomorphic-tools#46]
I'm trying to integrate webpack-isomorphic-tools with my project, which already uses Handlebars for rendering the root HTML page (via Express's view engine feature) and then embedding the root React component into the page, and was wondering what issues would arise or disadvantages I would have if I opt to use Handlebars over the example HTML component shown in the examples?

**Comment by halt-hammerzeit** [comment]
I don't see any difference so far.
You'll have your `webpack-isomorphic-tools` instance with `.assets()` method.
Supposedly it will be the same as for the React component shown in the readme.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
