### ISSUE TITLE
CSS Modules of css-loader support?

### ISSUE THREAD

**Issue by endaaman** [halt-hammerzeit/webpack-isomorphic-tools#57]
Hi.
I am using this and implementing server side rendering. But this does not work with `css-loader` with `modules` option like `?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]`.

If compiling css
```js
// a.css
.a {
  color: red;
}
```

and js importing it

```
var styles = require('./a.css')
console.log(styles) //  puts ->  Object {a: "a__a___3whEy"}
```

then `webpack-assets.json` should be

```json
{
  ...
  "assets": {
    "./a.css": {"a":"a__a___3whEy"}
  }
```

but in fact it will be like

```json
{
  ...
  "assets": {
    "./a.css": ".a__a___3whEy {\n  color: red;\n}\n"
  }
}
```

I think internal `require-hacker` ignores **`exports.locals`** even though `css-loader` generates css class map object as js module like

```
exports.locals = {
  className: "_23_aKvs-b8bW2Vg3fwHozO",
  subClass: "_13LGdX8RMStbBE9w-t0gZ1"
}
```

cf. [CSS Module section of css-loader](https://github.com/webpack/css-loader#css-modules)

Thanks.

**Comment by halt-hammerzeit** [comment]
It works with CSS modules.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#style-loader-css-stylesheets-with-css-modules-feature
Post your configuration.

**Comment by endaaman** [comment]
The repo is https://github.com/endaaman/rei_no_are

**Comment by halt-hammerzeit** [comment]
Ok, now compare these two and find the solution:
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#style-loader-css-stylesheets-with-css-modules-feature
https://github.com/endaaman/rei_no_are/blob/master/webpack-isomorphic-tools.js

**Comment by endaaman** [comment]
Ohh Im great sorry. I didnt see the section. Thank you very much.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
