### ISSUE TITLE
Images not displayed!

### ISSUE THREAD

**Issue by satimovm** [halt-hammerzeit/webpack-isomorphic-tools#69]
Hi!
I applied this tool for isomorphic app. Implemented all settings. Everything is working fine, but images are not displayed. Images  that were converted to  "data:img" is incorrect. 
Tried to reinstall url-loader plugin, no success. 
All settings made according to the instructions in your redme and also used https://github.com/erikras/react-redux-universal-hot-example app.
Any suggestions?

**Comment by halt-hammerzeit** [comment]
You can try to use `url-loader?limit=0` to prevent it from converting images to "data:img".
Disable `webpack-isomorphic-tools` first. If `url-loader` doesn't convert images to "data:img" with the tools disabled then it's unrelated to the tools.

**Comment by satimovm** [comment]
@halt-hammerzeit Hi, thanks for your reply. 
Could you please look at [my project ](https://github.com/satimovm/not-working-isomorphic-tool) (https://github.com/satimovm/not-working-isomorphic-tool). Because, may be I missed something when setting isomorphic tool

**Comment by halt-hammerzeit** [comment]
Well, you already have 
```

                {
                    test: webpackIsomorphicToolsPlugin.regular_expression('images'),
                    loader: 'url-loader?limit=10240'
                },
```

So you don't need

```

                {
                    test: /\.(jpe?g|png|gif)$/i,
                    loaders: ['file?name=[name].[ext]']
                },
```

Maybe it's causing something.

**Comment by satimovm** [comment]
@halt-hammerzeit 
:) Thank you very much. That was my fault!!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
