### ISSUE TITLE
how to hook require synchronously instead of do it in callback?

### ISSUE THREAD

**Issue by njugray** [halt-hammerzeit/webpack-isomorphic-tools#70]
`.server(project_path, [callback])` method  will waiting for `asserts.json` and run callback until require hook done.

But, in my project, `asserts.json`  already generated by webpack, server just need require hook,  and actually, my server use node workers which have a same entrance like `app.js`,  when startup, everything run synchronously, and callback in `.server()` method don't work.

So, I think a method to synchronously hook the require is needed.

**Comment by halt-hammerzeit** [comment]
What is the reason you don't move all your code to `server.js`?

**Comment by njugray** [comment]
@halt-hammerzeit 
My `server.js` startup a third-part framework based on koa,  and then invokes several node workers, each worker run `app.js` as common entrance. 

I can do anything in main thread, but that not work in workers, I have an only entrance `app.js` run in node worker, but have no where to put my callback to start server, because the runtime of `app.js` is inside the server.

I try to fork this repository and try to modify some code to run synchronously. it goes fine, and really works for me, but it's not much graceful, and maybe someone need this too.

**Comment by halt-hammerzeit** [comment]
@njugray anyway i didn't understand what's going on in your code. You can modify this library but Pull Requests aren't merged until proven really neccessary.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
