### ISSUE TITLE
Path to the javascript files

### ISSUE THREAD

**Issue by mrasoahaingo** [halt-hammerzeit/webpack-isomorphic-tools#73]
Hi,

How can I setup the tool to generate a webpack-assets.json with a relative path to my main bundle?
For now I get this:

````
{
  "javascript": {
    "main": "http://localhost:8080/dist/main-0310d6f32708926c578e.js"
  }
}
```
And this is my webpack config file

```
module.exports = {
  devtool: 'source-map',
  context: path.resolve(__dirname, '..'),
  entry: {
    'main': [
      './src/client.js'
    ]
  },
  output: {
    path: assetsPath,
    filename: '[name]-[chunkhash].js',
    chunkFilename: '[name]-[chunkhash].js',
    publicPath: '/dist/'
  }
  ...
}
```

Thanks for your help

**Comment by halt-hammerzeit** [comment]
The paths are generated relative to your webpack's context

```
{
    context: __dirname + "/app",
    entry: "./entry",
    output: {
        path: __dirname + "/dist",
        filename: "bundle.js"
    }
}
```

With no other options.

**Comment by mrasoahaingo** [comment]
Sorry I was't clear, how can I have a relative url of my main bundle like this

```
{
  "javascript": {
    "main": "/dist/main-0310d6f32708926c578e.js"
  }
}
```

**Comment by halt-hammerzeit** [comment]
The URLs for `javascript` files are prefixed with webpack's `publicPath`.
https://github.com/webpack/docs/wiki/configuration#outputpublicpath

**Comment by mrasoahaingo** [comment]
Oh okay, I didn't notice that, thank you!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
