### ISSUE TITLE
webpack 2 support? 

### ISSUE THREAD

**Issue by mmahalwy** [halt-hammerzeit/webpack-isomorphic-tools#75]
I gave webpack 2 a try and things exploded... didn't work :(

Does this support webpack 2?

**Comment by halt-hammerzeit** [comment]
Of course.
Be more specific

**Comment by mmahalwy** [comment]
I am getting style errors where css-modules is not working on the server. It is not loading the stylesheet.

**Comment by halt-hammerzeit** [comment]
Being specific assumes the corresponding logs at least.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by mmahalwy** [comment]
@halt-hammerzeit this is awesome! I am excited to give it a try very soon!
