### ISSUE TITLE
require.ensure ?

### ISSUE THREAD

**Issue by loudwinston** [halt-hammerzeit/webpack-isomorphic-tools#84]
Is it possible to add support for `require.ensure`?  We're using this for dynamically loading modules.

Currently I'm just adding this line at the top of every file that has to use `require.ensure`

```javascript
if (typeof require.ensure !== 'function') require.ensure = (d, c) => c(require);
```

**Comment by loudwinston** [comment]
For now I'm just adding the following in my startup script (thanks to https://github.com/webpack/webpack/issues/183#issuecomment-169186696)

```
let proto = Object.getPrototypeOf(require);
!proto.hasOwnProperty("ensure") && Object.defineProperties(proto, {
    "ensure": {
        value: function ensure(modules, callback) {
            callback(this);
        },
        writable: false
    },
    "include": {
        value: function include() {},
        writable: false
    }
});
```

**Comment by halt-hammerzeit** [comment]
Hmm, I see.

Yeah, the first way would be adding `require.ensure` to the top of every .js module.
Look at `inject_require_context` function:
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/index.js#L312
If you want you can write your `inject_require_ensure` function the same way and submit a Pull Request (along with a test case).

The prototype approach is interesting.
But I think it may be not an ideal solution since `require` is a function therefore `require.prototype` is `Function.prototype` and modifying that prototype may possibly conflict with other code.
Still I think this solution is okay enough.

**Comment by halt-hammerzeit** [comment]
I've done it.
Check `webpack-isomorphic-tools@2.3.1`

**Comment by halt-hammerzeit** [comment]
Hotfix.
Use `webpack-isomorphic-tools@2.3.2`
